### ISSUE TITLE
little bug and when to update sld code 👍 

### ISSUE THREAD

**Issue by MM-0712** [alibaba-damo-academy/SpokenNLP#4]
@lukecq1231 Hi, the readme of SLD seems a mistake as in the below.  And, I'm looking forward to your code. 
Thank you in advance for your contribution.
![image](https://github.com/alibaba-damo-academy/SpokenNLP/assets/68016601/7e611fd5-78bb-468b-9126-7f8843254b84)

**Comment by lukecq1231** [comment]
Thank you for expressing interest in our work and for pointing out the typo. I will address the typographical errors. Please expect the code to be available by early February.
